#ACTUALIZA LA LA SPCH CON LA SIGUIENTE LISTA DE SECURITIES

update("AGRO")
update("ALUA")
#MISSING update("APBR")
update("AUSO")
update("BBAR")
update("BHIP")
update("BMA")
update("BOLT")
update("BPAT")
update("BRIO")
update("BYMA")
update("CADO")
update("CAPX")
#update("CARC")
#update("CECO2")
#update("CELU")
update("CEPU")
update("CGPA2")
update("COME")
update("CRES")
update("CTIO")
update("CVH")
update("DGCU2")
#update("DOME")
#update("DYCA")
#update("EDLH")
update("EDN")
#update("EDSH")
#update("EMDE")
update("ESME")
update("FERR")
#update("FIPL")
#update("GAMI")
#update("GARO")
#update("GBAN")
update("GCLA")
update("GGAL")
#update("GRIM")
update("HARG")
#update("HAVA")
#update("INDU")
update("INTR")
update("INVJ")
#update("IRCP")
#update("IRSA")
update("LEDE")
update("LOMA")
#update("LONG")
update("METR")
update("MIRG")
update("MOLA")
update("MOLI")
#update("MORI")
update("OEST")
update("PAMP")
update("PATA")
#update("PATY")
#update("PGR")
#update("POLL")
update("RICH")
#update("RIGO")
#update("ROSE")
update("SAMI")
#update("SEMI")
update("SUPV")
update("TECO2")
#update("TGLT")
update("TGNO4")
update("TGSU2")
update("TRAN")
#MISSING update("TS")
update("TXAR")
update("VALO")
update("YPFD")


#BONOS

update("AY24")
update("AY24D")

#CEDEARS

update("GOLD")
update("VALE")
