#LISTA DE SECURITIES QUE ACTUALIZA EL MKT CAP USD

###PRUEBA
update_mkt_cap_usd("AGRO")
update_mkt_cap_usd("ALUA")
update_mkt_cap_usd("AUSO")
update_mkt_cap_usd("BBAR")
update_mkt_cap_usd("BHIP")
update_mkt_cap_usd("BMA")
update_mkt_cap_usd("BOLT")
update_mkt_cap_usd("BPAT")
update_mkt_cap_usd("BRIO")
update_mkt_cap_usd("BYMA")
update_mkt_cap_usd("CADO")
update_mkt_cap_usd("CAPX")
update_mkt_cap_usd("CEPU")
update_mkt_cap_usd("CGPA2")
update_mkt_cap_usd("COME")
update_mkt_cap_usd("CRES") #FALTA MAL LOS SPLITS REVISAR TODO
update_mkt_cap_usd("CTIO")
update_mkt_cap_usd("CVH")
update_mkt_cap_usd("DGCU2")
update_mkt_cap_usd("EDN") #FALTA LA SERIE LARGA DE BOLSAR
update_mkt_cap_usd("ESME")
update_mkt_cap_usd("FERR")
update_mkt_cap_usd("GCLA")
update_mkt_cap_usd("GGAL")
update_mkt_cap_usd("HARG")
update_mkt_cap_usd("INTR")
update_mkt_cap_usd("INVJ")
update_mkt_cap_usd("LEDE")
update_mkt_cap_usd("LOMA")
update_mkt_cap_usd("METR")
update_mkt_cap_usd("MIRG")
update_mkt_cap_usd("MOLA")
update_mkt_cap_usd("MOLI")
update_mkt_cap_usd("OEST")
update_mkt_cap_usd("PAMP")
update_mkt_cap_usd("PATA")
update_mkt_cap_usd("RICH")
update_mkt_cap_usd("SAMI")
update_mkt_cap_usd("SUPV")
update_mkt_cap_usd("TECO2")
update_mkt_cap_usd("TGNO4")
update_mkt_cap_usd("TGSU2")
update_mkt_cap_usd("TRAN")
update_mkt_cap_usd("TXAR")
update_mkt_cap_usd("VALO")
update_mkt_cap_usd("YPFD")

