#LISTA DE SECURITIES QUE CALCULA EL MKT CAP USDARS_PPP

update_mkt_cap_usdppp("AGRO")
update_mkt_cap_usdppp("ALUA")
update_mkt_cap_usdppp("AUSO")
update_mkt_cap_usdppp("BBAR")
update_mkt_cap_usdppp("BHIP")
update_mkt_cap_usdppp("BMA")
update_mkt_cap_usdppp("BOLT")
update_mkt_cap_usdppp("BPAT")
update_mkt_cap_usdppp("BRIO")
update_mkt_cap_usdppp("BYMA")
update_mkt_cap_usdppp("CADO")
update_mkt_cap_usdppp("CAPX")
update_mkt_cap_usdppp("CEPU")
update_mkt_cap_usdppp("CGPA2")
update_mkt_cap_usdppp("COME")
update_mkt_cap_usdppp("CRES") #FALTA MAL LOS SPLITS REVISAR TODO
update_mkt_cap_usdppp("CTIO")
update_mkt_cap_usdppp("CVH")
update_mkt_cap_usdppp("DGCU2")
update_mkt_cap_usdppp("EDN") #FALTA LA SERIE LARGA DE BOLSAR
update_mkt_cap_usdppp("ESME")
update_mkt_cap_usdppp("FERR")
update_mkt_cap_usdppp("GCLA")
update_mkt_cap_usdppp("GGAL")
update_mkt_cap_usdppp("HARG")
update_mkt_cap_usdppp("INTR")
update_mkt_cap_usdppp("INVJ")
update_mkt_cap_usdppp("LEDE")
update_mkt_cap_usdppp("LOMA")
update_mkt_cap_usdppp("METR")
update_mkt_cap_usdppp("MIRG")
update_mkt_cap_usdppp("MOLA")
update_mkt_cap_usdppp("MOLI")
update_mkt_cap_usdppp("OEST")
update_mkt_cap_usdppp("PAMP")
update_mkt_cap_usdppp("PATA")
update_mkt_cap_usdppp("RICH")
update_mkt_cap_usdppp("SAMI")
update_mkt_cap_usdppp("SUPV")
update_mkt_cap_usdppp("TECO2")
update_mkt_cap_usdppp("TGNO4")
update_mkt_cap_usdppp("TGSU2")
update_mkt_cap_usdppp("TRAN")
update_mkt_cap_usdppp("TXAR")
update_mkt_cap_usdppp("VALO")
update_mkt_cap_usdppp("YPFD")