

#LISTA DE SECURITIES

#LISTA DE SECURITIES MKT CAP USD
txt_spch_ARS("AGRO")
txt_spch_ARS("ALUA")
#MISSING txt_spch_ARS("APBR")
txt_spch_ARS("AUSO")
txt_spch_ARS("BBAR")
txt_spch_ARS("BHIP")
txt_spch_ARS("BMA")
txt_spch_ARS("BOLT")
txt_spch_ARS("BPAT")
txt_spch_ARS("BRIO")
txt_spch_ARS("BYMA")
txt_spch_ARS("CADO")
txt_spch_ARS("CAPX")
txt_spch_ARS("CEPU")
txt_spch_ARS("CGPA2")
txt_spch_ARS("COME")
txt_spch_ARS("CRES")
txt_spch_ARS("CTIO")
txt_spch_ARS("CVH")
txt_spch_ARS("DGCU2")
txt_spch_ARS("EDN")
txt_spch_ARS("ESME")
txt_spch_ARS("FERR")
txt_spch_ARS("GCLA")
txt_spch_ARS("GGAL")
txt_spch_ARS("HARG")
txt_spch_ARS("INTR")
txt_spch_ARS("INVJ")
txt_spch_ARS("LEDE")
txt_spch_ARS("LOMA")
txt_spch_ARS("METR")
txt_spch_ARS("MIRG")
txt_spch_ARS("MOLA")
txt_spch_ARS("MOLI")
txt_spch_ARS("OEST")
txt_spch_ARS("PAMP")
txt_spch_ARS("PATA")
txt_spch_ARS("RICH")
txt_spch_ARS("SAMI")
txt_spch_ARS("SUPV")
txt_spch_ARS("TECO2")
txt_spch_ARS("TGNO4")
txt_spch_ARS("TGSU2")
txt_spch_ARS("TRAN")
txt_spch_ARS("TXAR")
#MISSING txt_spch_ARS("TS")
txt_spch_ARS("VALO")
txt_spch_ARS("YPFD")

txt_spch_ARS_para_cedears("GOLD")
txt_spch_ARS_para_cedears("VALE")