

#LISTA DE SECURITIES MKT CAP USD
txt_mkt_cap_ars("AGRO")
txt_mkt_cap_ars("ALUA")
#MISSING txt_mkt_cap_ars("APBR")
txt_mkt_cap_ars("AUSO")
txt_mkt_cap_ars("BBAR")
txt_mkt_cap_ars("BHIP")
txt_mkt_cap_ars("BMA")
txt_mkt_cap_ars("BOLT")
txt_mkt_cap_ars("BPAT")
txt_mkt_cap_ars("BRIO")
txt_mkt_cap_ars("BYMA")
txt_mkt_cap_ars("CADO")
txt_mkt_cap_ars("CAPX")
txt_mkt_cap_ars("CEPU")
txt_mkt_cap_ars("CGPA2")
txt_mkt_cap_ars("COME")
txt_mkt_cap_ars("CRES")
txt_mkt_cap_ars("CTIO")
txt_mkt_cap_ars("CVH")
txt_mkt_cap_ars("DGCU2")
txt_mkt_cap_ars("EDN")
txt_mkt_cap_ars("ESME")
txt_mkt_cap_ars("FERR")
txt_mkt_cap_ars("GCLA")
txt_mkt_cap_ars("GGAL")
txt_mkt_cap_ars("HARG")
txt_mkt_cap_ars("INTR")
txt_mkt_cap_ars("INVJ")
txt_mkt_cap_ars("LEDE")
txt_mkt_cap_ars("LOMA")
txt_mkt_cap_ars("METR")
txt_mkt_cap_ars("MIRG")
txt_mkt_cap_ars("MOLA")
txt_mkt_cap_ars("MOLI")
txt_mkt_cap_ars("OEST")
txt_mkt_cap_ars("PAMP")
txt_mkt_cap_ars("PATA")
txt_mkt_cap_ars("RICH")
txt_mkt_cap_ars("SAMI")
txt_mkt_cap_ars("SUPV")
txt_mkt_cap_ars("TECO2")
txt_mkt_cap_ars("TGNO4")
txt_mkt_cap_ars("TGSU2")
txt_mkt_cap_ars("TRAN")
txt_mkt_cap_ars("TXAR")
#MISSING txt_mkt_cap_ars("TS")
txt_mkt_cap_ars("VALO")
txt_mkt_cap_ars("YPFD")

