

#LISTA DE SECURITIES MKT CAP USD
txt_mkt_cap_usd("AGRO")
txt_mkt_cap_usd("ALUA")
#MISSING txt_mkt_cap_usd("APBR")
txt_mkt_cap_usd("AUSO")
txt_mkt_cap_usd("BBAR")
txt_mkt_cap_usd("BHIP")
txt_mkt_cap_usd("BMA")
txt_mkt_cap_usd("BOLT")
txt_mkt_cap_usd("BPAT")
txt_mkt_cap_usd("BRIO")
txt_mkt_cap_usd("BYMA")
txt_mkt_cap_usd("CADO")
txt_mkt_cap_usd("CAPX")
txt_mkt_cap_usd("CEPU")
txt_mkt_cap_usd("CGPA2")
txt_mkt_cap_usd("COME")
txt_mkt_cap_usd("CRES")
txt_mkt_cap_usd("CTIO")
txt_mkt_cap_usd("CVH")
txt_mkt_cap_usd("DGCU2")
txt_mkt_cap_usd("EDN")
txt_mkt_cap_usd("ESME")
txt_mkt_cap_usd("FERR")
txt_mkt_cap_usd("GCLA")
txt_mkt_cap_usd("GGAL")
txt_mkt_cap_usd("HARG")
txt_mkt_cap_usd("INTR")
txt_mkt_cap_usd("INVJ")
txt_mkt_cap_usd("LEDE")
txt_mkt_cap_usd("LOMA")
txt_mkt_cap_usd("METR")
txt_mkt_cap_usd("MIRG")
txt_mkt_cap_usd("MOLA")
txt_mkt_cap_usd("MOLI")
txt_mkt_cap_usd("OEST")
txt_mkt_cap_usd("PAMP")
txt_mkt_cap_usd("PATA")
txt_mkt_cap_usd("RICH")
txt_mkt_cap_usd("SAMI")
txt_mkt_cap_usd("SUPV")
txt_mkt_cap_usd("TECO2")
txt_mkt_cap_usd("TGNO4")
txt_mkt_cap_usd("TGSU2")
txt_mkt_cap_usd("TRAN")
txt_mkt_cap_usd("TXAR")
#MISSING txt_mkt_cap_usd("TS")
txt_mkt_cap_usd("VALO")
txt_mkt_cap_usd("YPFD")

