

#LISTA DE SECURITIES MKT CAP USDPPP
txt_mkt_cap_usdppp("AGRO")
txt_mkt_cap_usdppp("ALUA")
#MISSING txt_mkt_cap_usdppp("APBR")
txt_mkt_cap_usdppp("AUSO")
txt_mkt_cap_usdppp("BBAR")
txt_mkt_cap_usdppp("BHIP")
txt_mkt_cap_usdppp("BMA")
txt_mkt_cap_usdppp("BOLT")
txt_mkt_cap_usdppp("BPAT")
txt_mkt_cap_usdppp("BRIO")
txt_mkt_cap_usdppp("BYMA")
txt_mkt_cap_usdppp("CADO")
txt_mkt_cap_usdppp("CAPX")
txt_mkt_cap_usdppp("CEPU")
txt_mkt_cap_usdppp("CGPA2")
txt_mkt_cap_usdppp("COME")
txt_mkt_cap_usdppp("CRES")
txt_mkt_cap_usdppp("CTIO")
txt_mkt_cap_usdppp("CVH")
txt_mkt_cap_usdppp("DGCU2")
txt_mkt_cap_usdppp("EDN")
txt_mkt_cap_usdppp("ESME")
txt_mkt_cap_usdppp("FERR")
txt_mkt_cap_usdppp("GCLA")
txt_mkt_cap_usdppp("GGAL")
txt_mkt_cap_usdppp("HARG")
txt_mkt_cap_usdppp("INTR")
txt_mkt_cap_usdppp("INVJ")
txt_mkt_cap_usdppp("LEDE")
txt_mkt_cap_usdppp("LOMA")
txt_mkt_cap_usdppp("METR")
txt_mkt_cap_usdppp("MIRG")
txt_mkt_cap_usdppp("MOLA")
txt_mkt_cap_usdppp("MOLI")
txt_mkt_cap_usdppp("OEST")
txt_mkt_cap_usdppp("PAMP")
txt_mkt_cap_usdppp("PATA")
txt_mkt_cap_usdppp("RICH")
txt_mkt_cap_usdppp("SAMI")
txt_mkt_cap_usdppp("SUPV")
txt_mkt_cap_usdppp("TECO2")
txt_mkt_cap_usdppp("TGNO4")
txt_mkt_cap_usdppp("TGSU2")
txt_mkt_cap_usdppp("TRAN")
txt_mkt_cap_usdppp("TXAR")
#MISSING txt_mkt_cap_usdppp("TS")
txt_mkt_cap_usdppp("VALO")
txt_mkt_cap_usdppp("YPFD")

