
#CHARTEA LA SERIES SPCHA PARA TODAS LAS ACCIONES

#PRUEBA    
chart("AGRO")
chart("ALUA")
#MISSING chart("APBR")
chart("AUSO")
chart("BBAR")
chart("BHIP")
chart("BMA")
chart("BOLT")
chart("BPAT")
chart("BRIO")
chart("BYMA")
chart("CADO")
chart("CAPX")
chart("CEPU")
chart("CGPA2")
chart("COME")
chart("CRES")
chart("CTIO")
chart("CVH")
chart("DGCU2")
chart("EDN")
chart("ESME")
chart("FERR")
chart("GCLA")
chart("GGAL")
chart("HARG")
chart("INTR")
chart("INVJ")
chart("LEDE")
chart("LOMA")
chart("METR")
chart("MIRG")
chart("MOLA")
chart("MOLI")
chart("OEST")
chart("PAMP")
chart("PATA")
chart("RICH")
chart("SAMI")
chart("SUPV")
chart("TECO2")
chart("TGNO4")
chart("TGSU2")
chart("TRAN")
chart("TXAR")
#MISSING chart("TS")
chart("VALO")
chart("YPFD")


