#LISTA DE SECURITIES QUE HACE EL CHART DEL MKT CAP EN ARS

chartmktcapars("AGRO")
chartmktcapars("ALUA")
chartmktcapars("AUSO")
chartmktcapars("BBAR")
chartmktcapars("BHIP")
chartmktcapars("BMA")
chartmktcapars("BOLT")
chartmktcapars("BPAT")
chartmktcapars("BRIO")
chartmktcapars("BYMA")
chartmktcapars("CADO")
chartmktcapars("CAPX")
chartmktcapars("CEPU")
chartmktcapars("CGPA2")
chartmktcapars("COME")
chartmktcapars("CRES") #FALTA MAL LOS SPLITS REVISAR TODO
chartmktcapars("CTIO")
chartmktcapars("CVH")
chartmktcapars("DGCU2")
chartmktcapars("EDN") #FALTA LA SERIE LARGA DE BOLSAR
chartmktcapars("ESME")
chartmktcapars("FERR")
chartmktcapars("GCLA")
chartmktcapars("GGAL")
chartmktcapars("HARG")
chartmktcapars("INTR")
chartmktcapars("INVJ")
chartmktcapars("LEDE")
chartmktcapars("LOMA")
chartmktcapars("METR")
chartmktcapars("MIRG")
chartmktcapars("MOLA")
chartmktcapars("MOLI")
chartmktcapars("OEST")
chartmktcapars("PAMP")
chartmktcapars("PATA")
chartmktcapars("RICH")
chartmktcapars("SAMI")
chartmktcapars("SUPV")
chartmktcapars("TECO2")
chartmktcapars("TGNO4")
chartmktcapars("TGSU2")
chartmktcapars("TRAN")
chartmktcapars("TXAR")
chartmktcapars("VALO")
chartmktcapars("YPFD")
