
# lISTA DE SECURITIES QUE ARMA EL CHART MKT CAP USD SERIE LARGA

chartmktcapusdserielarga("AGRO")
chartmktcapusdserielarga("ALUA")
#MISSING chartmktcapusdserielarga("APBR")
chartmktcapusdserielarga("AUSO")
chartmktcapusdserielarga("BBAR")
chartmktcapusdserielarga("BHIP")
chartmktcapusdserielarga("BMA")
chartmktcapusdserielarga("BOLT")
chartmktcapusdserielarga("BPAT")
chartmktcapusdserielarga("BRIO")
chartmktcapusdserielarga("BYMA")
chartmktcapusdserielarga("CADO")
chartmktcapusdserielarga("CAPX")
chartmktcapusdserielarga("CEPU")
chartmktcapusdserielarga("CGPA2")
chartmktcapusdserielarga("COME")
chartmktcapusdserielarga("CRES")
chartmktcapusdserielarga("CTIO")
chartmktcapusdserielarga("CVH")
chartmktcapusdserielarga("DGCU2")
chartmktcapusdserielarga("EDN")
chartmktcapusdserielarga("ESME")
chartmktcapusdserielarga("FERR")
chartmktcapusdserielarga("GCLA")
chartmktcapusdserielarga("GGAL")
chartmktcapusdserielarga("HARG")
chartmktcapusdserielarga("INTR")
chartmktcapusdserielarga("INVJ")
chartmktcapusdserielarga("LEDE")
chartmktcapusdserielarga("LOMA")
chartmktcapusdserielarga("METR")
chartmktcapusdserielarga("MIRG")
chartmktcapusdserielarga("MOLA")
chartmktcapusdserielarga("MOLI")
chartmktcapusdserielarga("OEST")
chartmktcapusdserielarga("PAMP")
chartmktcapusdserielarga("PATA")
chartmktcapusdserielarga("RICH")
chartmktcapusdserielarga("SAMI")
chartmktcapusdserielarga("SUPV")
chartmktcapusdserielarga("TECO2")
chartmktcapusdserielarga("TGNO4")
chartmktcapusdserielarga("TGSU2")
chartmktcapusdserielarga("TRAN")
chartmktcapusdserielarga("TXAR")
#MISSING chartmktcapusdserielarga("TS")
chartmktcapusdserielarga("VALO")
chartmktcapusdserielarga("YPFD")